server:
  port: 8080
  read_timeout: '3s'
  write_timeout: '3s'
  shutdown_timeout: '3s'

backends:
  - url: "http://localhost:9001"
    health_path: "/health"
    weight: 5
  - url: "http://localhost:9002"
    health_path: "/health"
    weight: 3
  - url: "http://localhost:9003"
    health_path: "/health"
    weight: 1

health_check:
  interval: '10s'

logger:
  level: debug
  format: json
  add_source: false